api:
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, default is recommended
  # 配置 API 服务监听的 IP 地址。0.0.0.0 表示监听所有网络接口，包括内部和外部 IP，建议默认使用此设置
  listenIP: 0.0.0.0
  # Listening ports; if multiple are configured, multiple instances will be launched, must be consistent with the number of prometheus.ports
  # 配置 API 服务监听的端口。这里配置了一个端口 10002。当配置多个端口时，会启动多个服务实例，这需要与 Prometheus 监控配置中的 ports 数量保持一致。
  ports: [ 10002 ]
  # API compression level; 0: default compression, 1: best compression, 2: best speed, -1: no compression
  # 配置 API 数据压缩的级别： 0-默认压缩,1-最佳压缩比,2-最快压缩速度,-1-不进行压缩
  compressionLevel: 0


prometheus:
  # Whether to enable prometheus
  # 是否启用prometheus监控功能
  enable: true
  # autoSetPorts indicates whether to automatically set the ports
  # 允许自动设置 Prometheus 的端口。开启自动设置后，prometheus.ports 参数不会生效，系统会自动和 api.ports 数量保持一致。
  autoSetPorts: true
  # Prometheus listening ports, must match the number of api.ports
  # It will only take effect when autoSetPorts is set to false.
  # 该项用于指定 Prometheus 的监听端口，必须和 api.ports 数量匹配。但当 autoSetPorts 为 true 时，此项将不会生效。
  ports:
  # This address can be accessed via a browser
  # 此项用于配置一个可以通过浏览器访问的 URL，通常用于指向 Grafana 的地址，以方便观察监控数据和统计图表。
  grafanaURL: 
